- name: Install nginx
  hosts: localhost
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: started