- name: user exists or not
  hosts: localhost
  
  tasks:
  - name: user exists or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print output
    ansible.builtin.debug:
     msg: "{{output.rc}}"

  - name: create user
    become: yes
    when: output.rc == 1
    ansible.builtin.user:
      name: roboshop

