- name: Vars at prompt
  hosts: test
  vars_prompt:
  - name: NAME
    prompt: Please enter user name
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true
  tasks:
  - name: display name
    ansible.builtin.debug:
      msg: "name is {{NAME}}"
  - name: display Password
    ansible.builtin.debug:
      msg: "Passowrd is {{PASSWORD}}"
  
