- name: preceedence of variable
  hosts: test
  # vars:
  #   Name: abc play
  
  #vars_files:
  #  var.yaml
  
  # vars_prompt:
  # - name: Name
  #   prompt: Enter Name
  #   private: false
  
  tasks:
  - name: print task var
    #vars: 
    #  Name: task var
    ansible.builtin.debug:
      msg: " Iam printing {{Name}}"

#1.args
#2.task
#3. files
#4.prompt
#5.play
