- name: Variables
  hosts: test
  #playlevel declaration
  vars:
    COURSE: DevOps
    DURATION: 3 months
  tasks:
  - name: print vars
    ansible.builtin.debug:
      msg: "Hello world"
  - name: print vars
    ansible.builtin.debug:
      msg: "I have joined {{COURSE}} and its duration is {{DURATION}}"
